hhu-propra2/abschlussprojekt-mopse

- gruppe.yml
Reverts hhu-propra2/abschlussprojekt-mopse#1
> Revert "Add information to gruppe.yml file"

- .github/workflows/gradle.yml
https://github.blog/changelog/2019-09-30-github-actions-event-filtering-updates/
> FIX: use different pattern

- doc/documentation/08_design_decisions.adoc
I added the documentation for the ArchUnit tests.
> ADD: Documentation for ArchUnit Tests

- doc/documentation/03_system_scope_and_context.adoc
After discussion with Jens and the "Gruppe" group we decided to request user permission with the user name.
> UPDATE: name instead of id

- src/main/java/mops/businesslogic/FileService.java
- src/main/java/mops/presentation/GroupController.java
Changes the id type in the existing controllers to long.
> UPDATE: use long for ids

- src/main/java/mops/presentation/DirectoryController.java
- src/main/java/mops/presentation/GroupController.java
with `@Param` the parameter is empty, it must be `@RequestAttribute`
> FIX: use request attribute instead of parameter

- src/test/java/mops/ArchitectureRulesTest.java
I added more ArchUnit Tests that test Controllers and check for potential Cycles.
> ADD: feature/more ArchUnit Tests

- .gitignore
Apparently leading slashes hava a meaning and un-ignoring via '!' is complicated.
> FIX: .gitignore

- src/main/java/mops/businesslogic/FileQuery.java
- src/main/java/mops/businesslogic/FileQueryBuilder.java
- src/main/java/mops/persistence/directory/DirectoryBuilder.java
- src/main/java/mops/persistence/file/FileInfoBuilder.java
- src/main/java/mops/persistence/permission/DirectoryPermissionsBuilder.java
> FIX: clarify builder exceptions

- src/main/java/mops/businesslogic/FileQueryBuilder.java
- src/test/java/mops/businesslogic/FileQueryTest.java
> ADD: Combination Test for File Query

- src/main/java/mops/businesslogic/DirectoryService.java
- src/main/java/mops/businesslogic/DirectoryServiceImpl.java
- src/main/java/mops/businesslogic/FileService.java
- src/main/java/mops/presentation/FileController.java
- src/test/java/mops/presentation/GroupControllerTest.java
Co-authored-by: Kai <49519629+KaFe23@users.noreply.github.com>
Closes #161
> FIX: exception flow in permission getter

- src/main/java/mops/businesslogic/DirectoryServiceImpl.java
- src/main/java/mops/businesslogic/FileInfoServiceImpl.java
- src/main/java/mops/businesslogic/FileServiceImpl.java
- src/main/java/mops/businesslogic/RoleServiceImpl.java
> FIX: MopsExceptions translated to german

- .idea/runConfigurations/Material1Application___prod.xml
- docker-compose.yml
- src/main/java/mops/businesslogic/DirectoryService.java
- src/main/java/mops/businesslogic/DirectoryServiceImpl.java
- src/main/java/mops/businesslogic/GroupServiceImpl.java
- src/main/java/mops/config/KeycloakConfig.java
- src/main/java/mops/config/SecurityConfig.java
- src/main/resources/application-prod.properties
- src/test/java/mops/businesslogic/DirectoryServiceTest.java
- src/test/java/mops/businesslogic/PermissionServiceTest.java
> ADD: make it work!

- README.md
- src/main/java/mops/businesslogic/DirectoryService.java
- src/main/java/mops/businesslogic/DirectoryServiceImpl.java
- src/main/java/mops/businesslogic/GroupService.java
- src/main/java/mops/businesslogic/GroupServiceImpl.java
- src/main/java/mops/persistence/DirectoryRepository.java
- src/main/java/mops/presentation/GroupController.java
- src/test/java/mops/businesslogic/DirectoryServiceTest.java
- src/test/java/mops/presentation/GroupControllerTest.java
> FIX: get or create root

- doc/documentation/03_system_scope_and_context.adoc
- doc/documentation/05_building_block_view.adoc
> ADD: Doc/group service

- doc/documentation/03_system_scope_and_context.adoc
- src/main/java/mops/businesslogic/GroupService.java
- src/main/java/mops/businesslogic/GroupServiceDevImpl.java
- src/main/java/mops/businesslogic/GroupServiceProdImpl.java
- src/main/java/mops/presentation/GroupsController.java
- src/test/java/mops/businesslogic/GroupServiceTest.java
- src/test/java/mops/presentation/GroupsControllerTest.java
> FIX: Hotfix/method names

- src/main/java/mops/businesslogic/FileService.java
- src/main/java/mops/businesslogic/FileServiceImpl.java
- src/main/java/mops/businesslogic/GarbageCollector.java
- src/test/java/mops/Material1ApplicationTests.java
- src/test/java/mops/SecurityTests.java
- src/test/java/mops/businesslogic/DirectoryServiceTest.java
- src/test/java/mops/businesslogic/GarbageCollectorTest.java
partially implements #181, but does not close it
> ADD: garbage collector

- src/main/java/mops/businesslogic/DirectoryServiceImpl.java
- src/main/resources/application.properties
- template.env
> ADD: env vars

- src/main/java/mops/businesslogic/prometheus/PrometheusComponent.java
- src/main/java/mops/config/SchedulingConfig.java
- src/main/java/mops/persistence/DirectoryRepository.java
- src/main/java/mops/persistence/FileInfoRepository.java
Co-Authored-By: Kai <49519629+KaFe23@users.noreply.github.com>
> FIX: add new gauges when there are new groups.

- src/main/java/mops/presentation/DirectoryController.java
- src/main/java/mops/presentation/FileController.java
- src/main/java/mops/presentation/GroupController.java
- src/main/java/mops/presentation/GroupsController.java
Add account to model
removed unnecessary parameters
closes #223
> FIX: controller

- src/main/java/mops/persistence/FileInfoRepository.java
- src/test/java/mops/persistence/file/FileInfoTest.java
> ADD: repository tests

- src/main/java/mops/businesslogic/file/FileServiceImpl.java
- src/main/resources/templates/directory.html
> FIX: empty folder or file

- src/main/java/mops/persistence/file/FileInfo.java
- src/main/resources/templates/directory.html
> ADD: byte representation

- src/main/resources/templates/directory.html
- src/main/resources/templates/files.html
> ADD: Owner to directory and search view. Fix Date TBD Bug

- src/main/java/mops/presentation/DirectoryController.java
- src/main/java/mops/presentation/form/FileQueryForm.java
- src/main/resources/templates/directory.html
- src/main/resources/templates/files.html
- src/main/resources/templates/groups.html
- src/test/java/mops/presentation/DirectoryControllerTest.java
- src/test/java/mops/presentation/form/FileQueryFormTest.java
closes #245 
Co-authored-by: Kai <49519629+KaFe23@users.noreply.github.com>
> UPDATE: back button

- src/main/java/mops/businesslogic/GarbageCollector.java
- src/main/java/mops/businesslogic/file/FileInfoService.java
- src/main/java/mops/businesslogic/file/FileInfoServiceImpl.java
- src/main/java/mops/persistence/FileInfoRepository.java
Finds all files that have directories that are non-existing. As in #273, there shouldn't ever be such db entries, but if they are ever there, they will be removed :)
> FEATURE: Garbage collector: remove "no directory"-orphans

- src/main/java/mops/businesslogic/security/SecurityServiceImpl.java
closes #277 
Co-Authored-By:  Ali Hassoun <ali-hassoun.97@hotmail.de>
> FIX: wrong error messages

- src/main/resources/templates/mops_error.html
> UPDATE: match image and bar width

- src/main/java/mops/businesslogic/directory/DirectoryServiceImpl.java
Co-Authored-by: Pascal Liedtke <pascal.liedtke@me.com>
Co-authored-by: Kai <49519629+KaFe23@users.noreply.github.com>
Co-Authored-by: Konstantin Schwarze <Konsicrafter@web.de>
> UPDATE: show duplication error for directories

- src/main/java/mops/presentation/Material1Controller.java
- src/main/resources/templates/mops_error.html
- src/main/resources/templates/overview.html
> ADD: logout and index redirection

- src/main/java/mops/presentation/DirectoryController.java
- src/test/java/mops/presentation/DirectoryControllerTest.java
@RutenkolkC we made it :wink: 
finalizes #302
> ADD: Feature/zip route

- src/main/java/mops/businesslogic/directory/DirectoryServiceImpl.java
- src/main/java/mops/businesslogic/group/GroupService.java
- src/main/java/mops/businesslogic/group/GroupServiceImpl.java
- src/main/java/mops/persistence/directory/DirectoryBuilder.java
- src/main/java/mops/persistence/file/FileInfoBuilder.java
- src/main/resources/schema.sql
- src/test/java/mops/businesslogic/directory/DirectoryServiceTest.java
- src/test/java/mops/businesslogic/security/PermissionServiceTest.java
- src/test/java/mops/businesslogic/security/SecurityServiceTest.java
- src/test/java/mops/persistence/DirectoryRepositoryTest.java
- src/test/java/mops/persistence/directory/DirectoryTest.java
- src/test/java/mops/presentation/GroupControllerTest.java
- src/test/resources/schema.sql
> ADD: change root directory name to group name

- src/main/java/mops/presentation/ExceptionController.java
- src/main/java/mops/presentation/error/ExceptionPresentationError.java
- src/main/java/mops/presentation/error/MessagePresentationError.java
- src/main/java/mops/presentation/error/PresentationError.java
> FIX: make MaxUploadSizeExceededException message german

- doc/documentation/04_solution_strategy.adoc
- prod.env
> ADD: env vars documentation

- doc/documentation/05_building_block_view.adoc
Reverts hhu-propra2/abschlussprojekt-mopse#342
> Revert "FIX: missing underscore"

- src/main/java/mops/businesslogic/directory/DirectoryServiceImpl.java
- src/main/resources/static/img/arrow-90deg-up.svg
- src/main/resources/static/img/download.svg
- src/main/resources/static/img/list.svg
- src/main/resources/templates/overview.html
Closes #347 
Can I get some suggestions where to put that menu, it looks kinda strange there.
> ADD: dropdown menu for current directory

- doc/documentation/05_building_block_view.adoc
- src/main/java/mops/businesslogic/GarbageCollector.java
- src/main/java/mops/businesslogic/directory/DirectoryService.java
- src/main/java/mops/businesslogic/directory/DirectoryServiceImpl.java
- src/main/java/mops/businesslogic/file/FileInfoServiceImpl.java
- src/main/java/mops/businesslogic/file/FileService.java
- src/main/java/mops/businesslogic/file/FileServiceImpl.java
- src/main/java/mops/persistence/DirectoryRepository.java
- src/test/java/mops/businesslogic/GarbageCollectorTest.java
> FEATURE: garbage collector final

- src/main/resources/templates/overview.html
Well, I don't know what to say but I don't know why this every worked.
> FIX: thymeleaf oddity

- src/main/java/mops/businesslogic/directory/DirectoryServiceImpl.java
- src/main/java/mops/businesslogic/file/FileInfoServiceImpl.java
- src/main/java/mops/businesslogic/group/GroupServiceImpl.java
- src/main/java/mops/businesslogic/permission/PermissionServiceImpl.java
> FIX: NoSuchElementException
